### PR TITLE
Fix amber2014 NME lib & OPLS2015 tip3p prms

### PR DESCRIPTION
**Pull request by aqvistlab**

### CODE REVIEW

**Comment by esguerra** [comment]
@aqvistlab 
Reveal yourself!
:smiley: 
No, but really, who are you?

**Comment by jesperswillem** [comment]
Hi, just to check I saw it correctly. Apparently a mismatch with water tip3p parameters for OPLS?

**Comment by aqvistlab** [comment]
Hey,
It's Florian, we just made a repository to gather some bugs and stuff we encounter. And I thought you guys would probably  want to fix these 2 things in the main repository. 
So the the tip3p waters currently present in opls2015 have non-zere lj parameters on the hydrogens which sometimes crashes Q5. And Miha found that there was a mistake in the amber library file, one of the capping residues has 3 bonds to one hydrogen and two missing bonds.

**Comment by jesperswillem** [comment]
Thanks for checking! I'll merge the pull request.

Cheers

**Comment by esguerra** [comment]
Hej hej Florian,
Good to know. Thanks for the explanation.

**Pull request merged**
